- hosts: localhost
  connection: local
  tasks:
  - name: "Generate a Key Pair"
    openssh_keypair:
      path: ~/.ssh/ansible_id_rsa
      state: present
  - name: "Create a KeyPair using existing public key"
    ec2_key:
      name: CloudFormationKeyPair
      key_material: "{{ lookup('file', '~/.ssh/ansible_id_rsa.pub') }}"
      state: present
  - name: "Create a simple stack"
    cloudformation:
      state: present
      stack_name: test-stack
      region: eu-west-2
      template: stack.yaml
  - cloudformation_info:
      stack_name: test-stack
      stack_resources: true
    register: output
  - ec2_instance_info:
      instance_ids: "{{ output['cloudformation']['test-stack']['stack_resource_list'] | json_query(query) }}"
    vars:
      query: "[?ResourceType=='AWS::EC2::Instance'].PhysicalResourceId"
    register: ec2
  - set_fact:
      ec2_instances: "{{ ec2['instances'] | map(attribute='public_dns_name') | list }}"
  - name: "build inventory"
    add_host:
      name: "{{ item }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=60'
    with_items: "{{ ec2_instances }}"

- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: "Wait for system to become reachable"
    wait_for_connection:
  - name: "Gather facts for first time"
    setup:
  - name: "Install Dependencies"
    apt:
      name: git
      update_cache: yes
      state: latest
  - name: "Install Pip"
    apt:
      name: python3-pip
      update_cache: yes
      state: present
  - name: update certificates
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: Add ubuntu user to the Docker group
    user:
      name: ubuntu
      groups:
      - docker
      shell: /bin/bash
  - name: "create etc/docker folder"
    file:
      path: /etc/docker
      state: directory
      owner: ubuntu
      group: ubuntu
    remote_user: ubuntu
  - name: "Copy daemon for registry connection"
    copy:
      src: /home/qa-admin/PracticalProject/daemon.json
      dest: /etc/docker/daemon.json
      owner: ubuntu
      group: ubuntu
    remote_user: ubuntu
  - name: docker service
    service:
      name: docker
      state: restarted
    remote_user: ubuntu
  - pip:
      executable: pip3
      name:
      - docker
      - docker-compose
      - jsondiff
  - git:
      repo: 'https://github.com/devops-cohort/Shaybs.git'
      dest: /home/ubuntu/Shaybs
      version: development-aws

  - name: build images2
    shell:
      cmd: "cd /home/ubuntu/Shaybs && docker-compose build"

  - name: initialise swarm
    docker_swarm:
      state: present
  - name: Deploy stack from a compose file
    docker_stack:
      state: present
      name: stack
      compose:
        - /home/ubuntu/Shaybs/docker-compose.yaml



